version: '2'
services:
  db:
    image: mysql:latest
    env_file: .env
    volumes:
      - ./mysql-data/:/var/lib/mysql/
  web:
    build:
      context: ./angular-rails-app/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file: .env
    environment:
      MYSQL_HOST: db
    volumes:
      - ./angular-rails-app/:/angular-rails-app/
    ports:
      - "3000:3000"
    depends_on:
      - db
  nb:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    environment:
      MYSQL_HOST: db
    volumes:
      - ./JPF/:/root/work/
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db:db
